version: '3.8'

services:
  ticketing-netsuite:
    build: .
    container_name: ticketing-netsuite
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - MAINTENANCE_MODE=true  # Set to true for maintenance mode
    command: ["sh", "-c", "if [ \"$MAINTENANCE_MODE\" = \"true\" ]; then node maintenance.mjs; else serve -s dist -l 7000; fi"]
